# Generated by Django 4.0.4 on 2022-05-01 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookWriting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='BookWriting.book'),
        ),
    ]
