# Generated by Django 4.0.4 on 2022-05-01 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookWriting', '0002_alter_section_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='is_parent',
        ),
        migrations.AlterField(
            model_name='section',
            name='parent_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_sections', to='BookWriting.section'),
        ),
    ]
