# Generated by Django 4.0.4 on 2022-05-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookWriting', '0003_remove_section_is_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='book',
        ),
        migrations.AddField(
            model_name='section',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
