# Generated by Django 4.0.4 on 2022-05-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookWriting', '0004_remove_section_book_section_is_parent_delete_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='is_parent',
            new_name='is_book',
        ),
    ]
